### ISSUE TITLE
blender-datasmith-export Error 

### ISSUE THREAD

**Issue by khaled957** [0xafbf/blender-datasmith-export#18]
Hi @0xafbf ,

I'm trying to export .datasmith file from blender, The issue is that I have a file which contains some models copied from another file inside the main project. However, I tried to export the **ONLY** models that were modeled in the main project , it worked normally. but when I tried to export the file with copied models inside, an error accrued as follows:

 Traceback (most recent call last):
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\__init__.py", line 56, in execute
    return export_datasmith.save(context, **keywords)
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1149, in save
    scene = collect_to_uscene(bpy.context)
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1105, in collect_to_uscene
    uscene.material_nodes = [collect_pbr_material(mat) for mat in uscene.materials]
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1105, in <listcomp>
    uscene.material_nodes = [collect_pbr_material(mat) for mat in uscene.materials]
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 804, in collect_pbr_material
    return pbr_nodetree_material(material)
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 736, in pbr_nodetree_material
    expressions = get_expression(surface_field, exp_list)
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 422, in get_expression
    return_exp = get_expression_inner(field, exp_list)
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 453, in get_expression_inner
    "BaseColor": get_expression(node.inputs['Base Color'], exp_list),
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 422, in get_expression
    return_exp = get_expression_inner(field, exp_list)
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 646, in get_expression_inner
    exp = exp_mixrgb(node, exp_list)
  File "C:\Users\khale\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 156, in exp_mixrgb
    n = Node("FunctionCall", { "Function": op_map_color[op]})
KeyError: 'MIX'

location: <unknown location>:-1

**Comment by khaled957** [comment]
Texture Mapping node should not be included in the material
