### ISSUE TITLE
Unable to export

### ISSUE THREAD

**Issue by Sachin9210** [0xafbf/blender-datasmith-export#26]
Hi. I tried to export the racer scene which we get from the blender market using the export addon. I am getting the error message as shown below.

Traceback (most recent call last):
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\__init__.py", line 75, in execute
    return export_datasmith.save(context, **keywords)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1467, in save
    collect_and_save(context, kwargs, basepath)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1366, in collect_and_save
    material_nodes = [collect_pbr_material(mat) for mat in unique_materials]
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1366, in <listcomp>
    material_nodes = [collect_pbr_material(mat) for mat in unique_materials]
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 913, in collect_pbr_material
    return pbr_nodetree_material(material)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 844, in pbr_nodetree_material
    expressions = get_expression(surface_field, exp_list)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 488, in get_expression
    return_exp = get_expression_inner(field, exp_list)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 637, in get_expression_inner
    expressions = get_expression(node.inputs[1], exp_list)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 488, in get_expression
    return_exp = get_expression_inner(field, exp_list)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 810, in get_expression_inner
    return exp_group(socket, exp_list)# TODO node trees can have multiple outputs
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 424, in exp_group
    inner_exp = get_expression(inner_socket, exp_list)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 488, in get_expression
    return_exp = get_expression_inner(field, exp_list)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 625, in get_expression_inner
    expressions = get_expression(node.inputs[0], exp_list)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 488, in get_expression
    return_exp = get_expression_inner(field, exp_list)
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 630, in get_expression_inner
    n.push(Node("0", expressions[name]))
  File "C:\Users\talkt\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-datasmith-export-master\data_types.py", line 75, in __init__
    assert type(attrs) is dict
AssertionError

location: <unknown location>:-1

**Comment by bushnaq12** [comment]
i get the same, why though?

**Comment by 0xafbf** [comment]
Hello @Sachin9210  and @bushnaq12 , thanks for writing.
Please join the discord server, so we can talk more closely, you can also submit troublesome scenes privately.
