### ISSUE TITLE
Error during Export 

### ISSUE THREAD

**Issue by chamindu530** [0xafbf/blender-datasmith-export#60]
Python: Traceback (most recent call last):
  File "C:\Users\chami\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-datasmith-export-master\__init__.py", line 101, in execute
    return export_datasmith.save(context, **keywords)
  File "C:\Users\chami\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2458, in save
    collect_and_save(context, kwargs, basepath)
  File "C:\Users\chami\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2332, in collect_and_save
    environment = collect_environment(context.scene.world)
  File "C:\Users\chami\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2000, in collect_environment
    background_node = output.inputs['Surface'].links[0].from_node
IndexError: tuple index out of range
![image](https://user-images.githubusercontent.com/58759023/209423553-82232bbb-133b-4117-bbd3-db90710f83b9.png)

**Comment by prasannapk213870** [comment]
![image](https://github.com/0xafbf/blender-datasmith-export/assets/144950764/522ea22f-bbc2-4d33-b61b-0c24b17af9fd)
 i have no idea what to do now ?

**Comment by prasannapk213870** [comment]
> Python: Traceback (most recent call last): File "C:\Users\chami\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-datasmith-export-master__init__.py", line 101, in execute return export_datasmith.save(context, **keywords) File "C:\Users\chami\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2458, in save collect_and_save(context, kwargs, basepath) File "C:\Users\chami\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2332, in collect_and_save environment = collect_environment(context.scene.world) File "C:\Users\chami\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2000, in collect_environment background_node = output.inputs['Surface'].links[0].from_node IndexError: tuple index out of range ![image](https://user-images.githubusercontent.com/58759023/209423553-82232bbb-133b-4117-bbd3-db90710f83b9.png)

hey! did you do any solution for that ?
