### ISSUE TITLE
PBR material blocks export

### ISSUE THREAD

**Issue by Twein2** [0xafbf/blender-datasmith-export#63]
I have a fairly simple PBR material generated depending on a slope. 
Without this material everything exports fine.

![image](https://user-images.githubusercontent.com/68532183/231180494-0facd66c-2f50-4c53-9d14-13f961a7c66c.png)

Here is a blend file https://we.tl/t-qqVmHAzupT

**Microsoft Edge says:**
_The error message AttributeError: 'NoneType' object has no attribute 'items' suggests that the variable expressions is None when the code is trying to access its items attribute. This could be due to the variable not being properly initialized or assigned a value before this line of code is executed. You may want to check the code to see where the variable expressions is defined and make sure it is assigned a value before this line of code is executed._

**Blender says:**
_Python: Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-datasmith-export-master\__init__.py", line 101, in execute
    return export_datasmith.save(context, **keywords)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2458, in save
    collect_and_save(context, kwargs, basepath)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2345, in collect_and_save
    material_nodes = [collect_pbr_material(mat) for mat in unique_materials]
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2345, in <listcomp>
    material_nodes = [collect_pbr_material(mat) for mat in unique_materials]
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1462, in collect_pbr_material
    return pbr_nodetree_material(material)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1389, in pbr_nodetree_material
    for key, value in expressions.items():
AttributeError: 'NoneType' object has no attribute 'items'_

**Comment by SuddenDevelopment** [comment]
this makes sense, I think it only knows what to do with basic BSDF materials.

**Comment by botero-dev** [comment]
Hello!

I just published the commercial version of this plugin as open source, please check out:
https://github.com/botero-dev/bl_datasmith/releases/tag/v1.1.12

I am closing this issue now so we can have a clean space to track new issues after this release.

Please test the new release and check if your issue was solved there. If not, please file a new issue.

Thanks in advance for your feedback. Best regards.
