### ISSUE TITLE
Error with Blendr 4.0

### ISSUE THREAD

**Issue by monnerHenster** [0xafbf/blender-datasmith-export#65]
Datasmith export error:
'NoneType' object has no attribute 'use_nodes'
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-datasmith-export-master\__init__.py", line 101, in execute
    return export_datasmith.save(context, **keywords)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2458, in save
    collect_and_save(context, kwargs, basepath)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 2332, in collect_and_save      
    environment = collect_environment(context.scene.world)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-datasmith-export-master\export_datasmith.py", line 1994, in collect_environment   
    if not world.use_nodes:
AttributeError: 'NoneType' object has no attribute 'use_nodes'

**Comment by emilsvfx** [comment]
yep the same

**Comment by xx3w** [comment]
same ;(

**Comment by fherx** [comment]
Same :/
